"""
predict.py — Full inference pipeline for the test set.

Generates:
  output/matching_results.tsv    — one row per S1 entity; matched_entity_ids pipe-delimited
  output/candidate_pairs.tsv     — all HNSW-retrieved pairs (already generated by blocking step,
                                   copied/referenced here for submission)

Usage:
    python -m src.model.predict \
        --candidates   output/candidate_pairs_test.tsv \
        --s1-tsv       dataset/test/source1.tsv \
        --s2-tsv       dataset/test/source2.tsv \
        --s3-tsv       dataset/test/source3.tsv \
        --s1-emb       .cache/embeddings/s1_test_embeddings.npy \
        --s2-emb       .cache/embeddings/s2_test_embeddings.npy \
        --s3-emb       .cache/embeddings/s3_test_embeddings.npy \
        --model-dir    .cache/model \
        --backend      xgboost \
        --output-dir   output
"""

from __future__ import annotations
import argparse
import pathlib
import pickle
import sys

import numpy as np
import pandas as pd
from tqdm import tqdm


def _load_tfidf(model_dir: pathlib.Path) -> tuple:
    with open(model_dir / "tfidf_name.pkl", "rb") as f:
        name_tfidf = pickle.load(f)
    with open(model_dir / "tfidf_addr.pkl", "rb") as f:
        addr_tfidf = pickle.load(f)
    return name_tfidf, addr_tfidf


def _load_threshold(model_dir: pathlib.Path, default: float = 0.5) -> float:
    tp = model_dir / "best_threshold.txt"
    if tp.exists():
        t = float(tp.read_text().strip())
        print(f"[predict] Using threshold = {t:.4f} (from {tp})")
        return t
    print(f"[predict] No threshold file found; using default = {default}")
    return default


def run_inference(
    pairs_df: pd.DataFrame,
    s1_df: pd.DataFrame,
    s2_df: pd.DataFrame,
    s3_df: pd.DataFrame,
    emb_s1: np.ndarray,
    emb_s2: np.ndarray,
    emb_s3: np.ndarray,
    clf,
    feature_names: list[str],
    name_tfidf,
    addr_tfidf,
    threshold: float,
    all_s1_ids: list[str],
    output_dir: str | pathlib.Path,
) -> pd.DataFrame:
    sys.path.insert(0, str(pathlib.Path(__file__).parents[3]))
    from src.features.pairwise_features import compute_features, FEATURE_COLS

    output_dir = pathlib.Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"[predict] Computing features for {len(pairs_df)} pairs…")
    feat_df = compute_features(
        pairs_df, s1_df, s2_df, s3_df,
        emb_s1, emb_s2, emb_s3,
        name_tfidf=name_tfidf,
        addr_tfidf=addr_tfidf,
    )

    X = feat_df[FEATURE_COLS].values.astype(np.float32)
    proba = clf.predict_proba(X)[:, 1]

    pairs_df = pairs_df.copy()
    pairs_df["prob"] = proba

    # --- matching_results.tsv ---
    matched = pairs_df[pairs_df["prob"] >= threshold]
    grouped = (
        matched.groupby("source1_entity_id")["candidate_entity_id"]
        .apply(lambda ids: "|".join(sorted(set(ids))))
        .reset_index()
        .rename(columns={"candidate_entity_id": "matched_entity_ids"})
    )
    all_s1 = pd.DataFrame({"source1_entity_id": all_s1_ids})
    results = all_s1.merge(grouped, on="source1_entity_id", how="left")
    results["matched_entity_ids"] = results["matched_entity_ids"].fillna("")

    results_path = output_dir / "matching_results.tsv"
    results.to_csv(str(results_path), sep="\t", index=False)
    print(f"[predict] Wrote matching_results.tsv → {results_path}")
    print(f"[predict] Entities with ≥1 match: {(results['matched_entity_ids'] != '').sum()}")
    print(f"[predict] Singletons (empty):      {(results['matched_entity_ids'] == '').sum()}")

    return results


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _main() -> None:
    sys.path.insert(0, str(pathlib.Path(__file__).parents[3]))
    from src.preprocessing.load_data import load_source
    from src.preprocessing.normalize_names import normalize_name_series
    from src.preprocessing.normalize_addresses import normalize_address_series
    from src.model.train_classifier import load_model

    parser = argparse.ArgumentParser()
    parser.add_argument("--candidates",  required=True)
    parser.add_argument("--s1-tsv",      required=True)
    parser.add_argument("--s2-tsv",      required=True)
    parser.add_argument("--s3-tsv",      required=True)
    parser.add_argument("--s1-emb",      required=True)
    parser.add_argument("--s2-emb",      required=True)
    parser.add_argument("--s3-emb",      required=True)
    parser.add_argument("--model-dir",   default=".cache/model")
    parser.add_argument("--backend",     default="xgboost")
    parser.add_argument("--output-dir",  default="output")
    parser.add_argument("--threshold",   type=float, default=None,
                        help="Override threshold (else loaded from model-dir)")
    args = parser.parse_args()

    pairs_df = pd.read_csv(args.candidates, sep="\t", dtype=str, keep_default_na=False)
    s1_df    = load_source(args.s1_tsv)
    s2_df    = load_source(args.s2_tsv)
    s3_df    = load_source(args.s3_tsv)
    for df in (s1_df, s2_df, s3_df):
        df["norm_name"]    = normalize_name_series(df["business_name"])
        df["norm_address"] = normalize_address_series(df["business_address"])

    emb_s1 = np.load(args.s1_emb)
    emb_s2 = np.load(args.s2_emb)
    emb_s3 = np.load(args.s3_emb)

    model_dir = pathlib.Path(args.model_dir)
    model_bundle = load_model(model_dir, args.backend)
    clf          = model_bundle["clf"]
    feature_names = model_bundle["features"]

    name_tfidf, addr_tfidf = _load_tfidf(model_dir)
    threshold = args.threshold if args.threshold is not None else _load_threshold(model_dir)

    all_s1_ids = list(s1_df["entity_id"])

    run_inference(
        pairs_df, s1_df, s2_df, s3_df,
        emb_s1, emb_s2, emb_s3,
        clf, feature_names, name_tfidf, addr_tfidf,
        threshold, all_s1_ids, args.output_dir,
    )
    print("[predict] Done.")


if __name__ == "__main__":
    _main()
